face_mask_pth_name: face_mask_model.pth
face_mask_onnx_name: face_mask_model.onnx

dataset_path: ~/ml-dataset/processed-face-mask

model_pth_out_dir: output/face_mask_detection/pth
model_onnx_out_dir: output/face_mask_detection/onnx

input_size: 112
batch_size: 32
epochs: 20
learning_rate: 0.001

num_classes: 5
 
device: cuda

model:
  name: mobilenetv3_small
  pretrained: true
