face_recognition:
  model:
    name: buffalo_l
    det_size: [320, 320]
    ctx_id: 0

  alignment:
    image_size: 112

  paths:
    config_path: core/face_recognition/configs/config.yml
    output_root: output/face_recognition
    raw_dataset: output/face_recognition/datasets/raw
    aligned_faces: output/face_recognition/datasets/aligned_faces
    embeddings: output/face_recognition/datasets/embeddings
    indexes: output/face_recognition/datasets/indexes
