enrollment:

  camera:
    camera_id: 0
    width: 1280
    height: 720
    fps: 30

  face_detection:
    model_name: buffalo_l
    ctx_id: 0
    det_size: [320, 320]
    min_face_size: 120
    max_faces: 1

  quality:
    blur_threshold: 100
    brightness_min: 70
    brightness_max: 180

  stability:
    history_size: 10

    center_std_max: 12
    center_std_y_max: 12

    yaw_std_max: 3
    pitch_std_max: 3

  poses:

    required_poses:
      - front
      - left
      - right
      - up
      - down

    optional_poses:
      - mask
      - glasses

  pipeline:
    - Align Face
    - Generate Embedding
    - Build FAISS Index
    - Generate dataset report

  performance:
    inference_sleep_sec: 0.03

  color:
    detection:
      bbox:
        green: [0, 255, 0]    # green
        orange: [0, 165, 255] # orange
        red: [0, 0, 255]      # red

    overlay:
      fps: [0, 255, 0]    # green
      guide: [0, 255, 0]  # green
      text: [0, 255, 0]   # green