enrollment:

  camera:
    camera_id: 0
    width: 1280
    height: 720
    fps: 30

  face_detection:
    model_name: buffalo_l
    ctx_id: 0
    det_size: [320, 320]
    min_face_size: 120
    max_faces: 1

  quality:
    blur_threshold: 100
    brightness_min: 70
    brightness_max: 180

  stability:
    history_size: 10

    center_std_max: 12
    center_std_y_max: 12

    yaw_std_max: 3
    pitch_std_max: 3

  workflow:

    required_poses:
      - front
      - left
      - right
      - up
      - down

    optional_poses:
      - mask
      - glasses

  poses:

    front:
      yaw_min: -10
      yaw_max: 10
      pitch_min: -10
      pitch_max: 10

    left:
      yaw_min: -45
      yaw_max: -18
      pitch_min: -12
      pitch_max: 12

    right:
      yaw_min: 18
      yaw_max: 45
      pitch_min: -12
      pitch_max: 12

    up:
      yaw_min: -12
      yaw_max: 12
      pitch_min: 15
      pitch_max: 35

    down:
      yaw_min: -12
      yaw_max: 12
      pitch_min: -35
      pitch_max: -15

    mask:
      yaw_min: -12
      yaw_max: 12
      pitch_min: -12
      pitch_max: 12

    glasses:
      yaw_min: -12
      yaw_max: 12
      pitch_min: -12
      pitch_max: 12

  performance:
    inference_sleep_sec: 0.03